services:
  apache82:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: flarum-svc82
    ports:
      - "80:8080"
    volumes:
      - ./config.php:/var/www/config.php:delegated
      - ./extend.php:/var/www/extend.php:delegated
      - ./storage:/var/www/storage:delegated
      - ./vendor:/var/www/vendor:delegated
      - ./workbench:/var/www/workbench:delegated
      - ./public:/var/www/public:delegated
    depends_on:
      - flarum82-db
    environment:
      APACHE_LOG_DIR: /var/www/storage/logs

      MYSQL_USER: flarum
      MYSQL_PASSWORD: flarum
      MYSQL_DATABASE: flarum
      MYSQL_HOST: flarumdb82
      MYSQL_PORT: 3306
      DB_DRIVER: mysql

      BASE_URL: "http://localhost"

      DEBUG: "true"
      LOCAL: "true"

  flarum82-db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: flarumdb82
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: flarum
      MYSQL_PASSWORD: flarum
      MYSQL_DATABASE: flarum
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database:/var/lib/mysql:delegated
    ports:
      - "127.0.0.1:3306:3306"

  flarum-pma:
    image: phpmyadmin:latest
    container_name: flarumpma82
    ports:
      - "127.0.0.1:8002:80"
    depends_on:
      - flarum82-db
    environment:
      PMA_HOSTS: "flarumdb82"
      PMA_VERBOSES: "Flarum Database"
      PMA_USER: flarum
      PMA_PASSWORD: flarum

volumes:
  database:
    name: flarum82-db
